### ISSUE TITLE
Restructuring our source code

### ISSUE THREAD

**Issue by bdecato** [Epigenomics-Screw/Screw#11]
It may be good to get rid of the "bin" naming for our scripts, because "bin" is typically associated with binaries, which have no place in github repos.

Also, it may be good to have a "src" directory that contains both "cwl" and "scripts", even though CWL isn't strictly source code.

I wanted to get opinions before making this change. @neksa @oneillkza ?

**Comment by neksa** [comment]
I don't see any problem with scripts in "bin", but "scripts" sounds reasonable. so +1 for "bin -> scripts". 
Regarding /src/cwl - it may be a bit impractical as all pointers to cwl files (e.g. on Dockstore) will have to be a bit longer. Other than that my opinion on src/cwl is neutral.

**Comment by oneillkza** [comment]
I don't mind too much -- on Unix, bin just ends up being a path for executables (which may include scripts), which is why I put it there in the first place, but if you'd rather it be called scripts, I don't mind.

I'd prefer to keep both cwl and the executables directory at the top level, though -- they're both pretty crucial to the project, so I think it would be better not to bury them.

**Comment by oneillkza** [comment]
Deciding on this should happen as a group project at the beginning of Hackseq 2017
