### ISSUE TITLE
Set up Quay.io image to rebuild on changes to Github Dockerfile

### ISSUE THREAD

**Issue by oneillkza** [Epigenomics-Screw/Screw#14]
It looks like it's possible to set up quay.io to rebuild the image based on a Github repo. @neksa, you could do this, but it might be easier if you set me as admin on the https://quay.io/repository/neksa/screw-tool repo (my quay.io username is the same as Github -- oneillkza). If you do that, I can set up the auto-build.

**Comment by neksa** [comment]
I'll take care of that, currently Docker files were sort of setup logs, because I have manually configured the images. I have a massive Docker update coming. 
Previously I created an organization on quay.io ncbi_hackathons  https://quay.io/repository/ncbi_hackathons/linux_base
But that was before we moved GitHub repo to Epigenomics-screw
I'll upload create new docker images as GitHub auto pull under epigenomicscrew organization on quay.io and will make you an admin.

**Comment by oneillkza** [comment]
Thanks! I've accepted the invitation to join the group. Unfortunately I don't have Docker at work (haven't yet persuaded Systems her to allow it), but will test on my home machine.

**Comment by oneillkza** [comment]
OK, looks like I've got the build trigger working!

**Comment by neksa** [comment]
Great, it did not not work for a branch pushes for some reason.
